name = "GembaPay Payments"
type = "payments_app_credit_card_offsite"
targeting_version = "1.0.0"

[targeting]
payment_session_resolve = "src/resolve.js"
payment_session_reject = "src/reject.js"
payment_session_pending = "src/pending.js"
refund_session_resolve = "src/refund-resolve.js"
refund_session_reject = "src/refund-reject.js"

[ui]
checkout_payment_method_fields = "src/checkout-ui.jsx"

[payment_experience]
redirect_url = "https://payment.gembapay.com/checkout/{orderId}"

[ui.paths]
default = "/"

[input.metafields]

[build]
command = ""
